### ISSUE TITLE
No health regen

### ISSUE THREAD

**Issue by SummitSummit** [squeek502/HungerInPeace#1]
Just loaded this onto my server instead of Harder Peaceful, and while Spice of Life now seems to be working properly, we are not regenerating health, even with full food.

**Comment by squeek502** [comment]
Can't reproduce this. Please post your full mod list.

**Comment by SummitSummit** [comment]
It's basically a slightly modified version of the new Direwolf20 FTB pack, here they are:
Baubles-1.7.10-1.0.1.8
CodeChickenLib-1.7.10-1.1.1.105-universal
ForgeMultipart-1.7.10-1.1.0.310-universal
[1.7.10]DamageIndicatorsMod-3.2.0
AOBD-2.2.5
AppleCore-mc1.7.10-1.0.0
appliedenergistics2-rv1-stable-1
Aroma1997Core-1.7.10-1.0.2.9
AromaBackup-1.7.10-0.0.0.4
BetterTitleScreen-1.7.10-1.1
BiblioCraft[v1.8.1][MC1.7.10]
BiblioWoods[Forestry][v1.6]
BiblioWoods[Highlands][v1.4]
BiblioWoods[Natura][v1.4]
BigReactors-0.4.0rc10
binnie-mods-2.0-dev5
Blood Magic-v1.2.0a(1.7.10)
Botania r1.2-131
buildcraft-6.1.5n
Carpenter's Blocks v3.2.8 - MC 1.7.10
ChickenChunks-1.7.10-1.3.4.13-universal
Chisel-1.7.10-1.5.7
CodeChickenCore-1.7.10-1.0.4.29-universal
CoFHCore-[1.7.10]3.0.0B6-32
CoFHLib-[1.7.10]1.0.0B6-26
CompactSolars-1.7.10-4.4.37.314-universal
ComputerCraft1.65
cookiecore-1.3.0
denseores-1.5
EnderIO-1.7.10-2.1.7.254
EnderStorage-1.7.10-1.4.5.24-universal
enetbridge-1.4
extrautilities-1.1.0k
fastcraft-1.9
FastLeafDecay-1.7.10-1.0
forestry_1.7.10-3.1.1.4
funky-locomotion-1.7.10-beta-2
HelpFixer-1.0.1
Highlands-1.7.2-v-2.2.2
HungerInPeace-mc1.7.10-1.0.0
IC2NuclearControl-2.0.5b-Unicorn
iChunUtil-4.0.0
IguanaTinkerTweaks-1.7.10-2.0.6
industrialcraft-2-2.2.648-experimental
INpureCore-[1.7.10]1.0.0B1-1
InventoryTweaks-1.59-dev-156
ironchest-1.7.10-6.0.60.741-universal
Jabba-1.1.4_1.7.10
JourneyMap5.0.0RC2_Unlimited_MC1.7.10
magicbees-1.7.10-2.1.22
Mantle-1.7.10-0.3.2
MCA-1.7.10-4.1.5-universal
MineFactoryReloaded-[1.7.10]2.8.0RC3-591
MineMenu-1.7.10-1.1.8.B40-universal
MineTweaker3-1.7.10-3.0.9B
MobiusCore-1.2.3_1.7.10
mystcraft-1.7.10-0.11.0.00
natura-1.7.10-2.2.0.1
neiaddons-mc1710-1.12.3.11
NEIIntegration-MC1.7.10-1.0.0
NEIPlugins-MC1.7.10-1.1.0.11-unofficial
NotEnoughCodecs-1.7.10-0.3-snapshot-11
NotEnoughItems-1.7.10-1.0.3.64-universal
ObsidiPlates-1.7.10-universal-3.0.0.18
OpenBlocks-1.7.10-1.3-snapshot-433
OpenModsLib-1.7.10-0.6-snapshot-224
OpenPeripheralAddons-1.7.10-0.2.0-snapshot-122
OpenPeripheralCore-1.7.10-0.5.0-snapshot-142
Pam's HarvestCraft 1.7.10c
Pam's Mob Drop Crops 1.7.10a
PlayerAPI-1.7.10-1.1
ProjectRed-Base-1.7.10-4.5.1.51
ProjectRed-Compat-1.7.10-4.5.1.51
ProjectRed-Integration-1.7.10-4.5.1.51
ProjectRed-Lighting-1.7.10-4.5.1.51
ProjectRed-World-1.7.10-4.5.1.51
RadixCore-1.7.10-1.3.4-universal
Railcraft_1.7.10-9.3.3.0
RedstoneArsenal-[1.7.10]1.1.0B4-10
slick-util
SmartCore-1.7.10-1.0
SmartMoving-1.7.10-15.2
SmartRender-1.7.10-2.0
SpiceOfLife-mc1.7.10-1.2.2
StevesCarts2.0.0.b18
TConstruct-1.7.10-1.7.1c
Thaumcraft-1.7.10-4.2.1.4
ThaumicExploration-1.7.10-1.1-22
ThaumicTinkerer-2.5-1.7.10-158
ThermalExpansion-[1.7.10]4.0.0B5-13
ThermalFoundation-[1.7.10]1.0.0B3-8
TiCTooltips-mc1.7.10-1.1.11b
TMechworks-1.7.10-0.2.10
Translocator-1.7.10-1.1.1.12-universal
TSteelworks-1.7.10-1.0.6
twilightforest-1.7.10-2.3.1
VeinMiner-1.7.10_0.21.1
Waila-1.5.4a_1.7.10
WailaHarvestability-mc1.7.x-1.1.0
WR-CBE-1.7.10-1.4.1.6-universal

**Comment by squeek502** [comment]
This is most likely due to Harder Peaceful forcefully setting the gamerule 'naturalRegeneration' to false, which disables all health regen from food ([see the Minecraft wiki](http://minecraft.gamepedia.com/Commands#gamerule)).

You can check the current setting by using the command:

```
/gamerule naturalRegeneration
```

and turn it back on by using the command:

```
/gamerule naturalRegeneration true
```

Also, as an aside, you might want to [update AppleCore to the latest version](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2222837-applecore-an-api-for-modifying-the-food-and-hunger) (1.0.1).

**Comment by SummitSummit** [comment]
Thank you very much.  You sir, are a genius.  I've never even heard of that game rule.  I'll update AppleCore then next time I reboot the server.  Thanks again.
